import {test,expect} from '@playwright/test'

test('navigation, import controls, and no horizontal page overflow',async({page})=>{
  const errors:string[]=[]
  page.on('pageerror',error=>errors.push(error.message))
  await page.goto('/')
  await expect(page.getByRole('heading',{name:'Dataset workspace',exact:true})).toBeVisible()
  await expect.poll(()=>page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth+1)).toBe(true)
  await page.getByRole('button',{name:'Import data',exact:true}).click()
  await expect(page.getByRole('dialog')).toBeVisible()
  await page.getByLabel('Input layout').selectOption('recording')
  await expect(page.getByText('Recording channels',{exact:true})).toBeVisible()
  await page.getByRole('button',{name:'Close dialog'}).click()
  for(const [url,title] of [['/algorithms','Algorithms with a clear contract'],['/experiments','Experiment workbench'],['/events','Event lab']]){
    await page.goto(url)
    await expect(page.getByRole('heading',{name:title,exact:true})).toBeVisible()
    await expect.poll(()=>page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth+1)).toBe(true)
  }
  expect(errors).toEqual([])
})

test('real interval explorer renders all analysis views',async({page,request})=>{
  const datasets=await (await request.get('/api/v1/datasets')).json()
  const dataset=datasets.find((d:any)=>d.format==='wide_ami')
  expect(dataset,'Register the supplied AMI files before browser verification').toBeTruthy()
  const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message))
  await page.goto('/explorer?dataset='+dataset.id)
  await expect(page.getByRole('heading',{name:'Measurement explorer',exact:true})).toBeVisible()
  await expect(page.locator('.js-plotly-plot')).toBeVisible()
  await expect(page.locator('.scatterlayer path.js-line').first()).toBeVisible()
  for(const view of ['Daily profile','Seasonal','Calendar heatmap','Distribution']){
    await page.getByRole('button',{name:view,exact:true}).click()
    await expect(page.getByRole('img',{name:view,exact:true})).toBeVisible()
    await expect(page.locator('.error')).toHaveCount(0)
  }
  await page.getByRole('button',{name:'Review labels',exact:true}).click()
  await expect(page.getByRole('dialog')).toBeVisible()
  await expect(page.getByLabel('Evidence source or review note')).toBeVisible()
  await page.getByRole('button',{name:'Close dialog'}).click()
  expect(errors).toEqual([])
})

test('event recording, native zoom, replay, and annotation controls',async({page,request})=>{
  const datasets=await (await request.get('/api/v1/datasets')).json()
  const recording=datasets.find((d:any)=>d.format==='recording'&&d.synthetic&&d.duration_seconds>=10&&d.channels.some((c:any)=>c.name==='power'))
  expect(recording,'Generate a synthetic recording before browser verification').toBeTruthy()
  const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message))
  await page.goto('/events')
  await page.getByRole('combobox',{name:'Recording',exact:true}).selectOption(recording.id)
  await expect(page.getByRole('combobox',{name:'Detector adapter',exact:true})).toHaveValue('baseline-events')
  await expect(page.locator('.js-plotly-plot')).toBeVisible()
  await page.locator('.inline-actions').getByRole('button',{name:'Zoom in',exact:true}).click()
  await expect(page.getByText('native samples',{exact:true})).toBeVisible()
  await page.getByRole('button',{name:'Start replay',exact:true}).click()
  await expect(page.getByRole('button',{name:'Pause replay',exact:true})).toBeVisible()
  await expect.poll(()=>page.locator('.replay-clock').innerText()).not.toBe('0.00 s')
  await page.getByRole('button',{name:'Pause replay',exact:true}).click()
  await page.getByRole('button',{name:'Annotate',exact:true}).click()
  await expect(page.getByLabel('Annotation type')).toBeVisible()
  await page.getByRole('button',{name:'Close dialog'}).click()
  await expect(page.locator('.error')).toHaveCount(0)
  await expect.poll(()=>page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth+1)).toBe(true)
  expect(errors).toEqual([])
})

test('classification configuration and completed result review',async({page,request})=>{
  await page.goto('/experiments')
  await page.getByRole('button',{name:'New experiment',exact:true}).click()
  await page.getByRole('combobox',{name:'Target',exact:true}).selectOption('EV')
  await page.getByLabel('Label evidence policy').selectOption('heuristic')
  await expect.poll(()=>page.locator('dialog form').evaluate((form:HTMLFormElement)=>form.checkValidity())).toBe(true)
  await expect(page.getByText('This run measures agreement with unvalidated screening rules.',{exact:false})).toBeVisible()
  await page.getByRole('button',{name:'Close dialog'}).click()
  const runs=await (await request.get('/api/v1/experiments')).json()
  const result=runs.find((r:any)=>r.kind==='classification')
  expect(result,'Complete a classifier benchmark before browser verification').toBeTruthy()
  await page.getByRole('button',{name:result.name,exact:true}).click()
  await expect(page.getByRole('link',{name:'Export bundle',exact:true})).toBeVisible()
  await page.getByRole('button',{name:'Prediction review',exact:true}).click()
  await expect(page.getByLabel('Errors only')).toBeVisible()
  await page.getByRole('button',{name:'Provenance',exact:true}).click()
  await expect(page.locator('.code')).toContainText('split_id')
})
